package com.jplusplus.modules;

/**
 * Created by Joshua on 11/15/2017.
 */
public enum TokenType {
    IDENTIFIER,
    ARITHMETIC_OPERATOR,
    DATA_TYPE,
    IF,
    ELSEIF,
    ELSE,
    COND,
    ASSIGNMENT,
    WHILE,
    DO_WHILE,
    FOR,
    RELATIONAL_OPERATOR,
    LITERAL,
    LINE_TERMINATOR,
    IF_TERMINATOR,
    ELSEIF_TERMINATOR,
    ELSE_TERMINATOR,
    WHILE_TERMINATOR,
    FOR_TERMINATOR,
    DO_WHILE_TERMINATOR,
    INPUT_INTEGER_OPERATION,
    INPUT_DOUBLE_OPERATION,
    INPUT_CHARACTER_OPERATION,
    INPUT_STRING_OPERATION,
    INPUT_BOOLEAN_OPERATION,
    OUTPUT_OPERATION,
    COMMENT;
}